### ISSUE TITLE
FeatureRequest: label cells as desired for output in confluence

### ISSUE THREAD

**Issue by no-one2k** [sancau/dstrace#2]
it would be great to have possibility 
- to mark code cells in notebooks with special label (eg. "#TOWIKI") so only marked cells produce output to confluence page
- to set option for whole notebook whether to use all cells or only marked

![image](https://user-images.githubusercontent.com/9806695/76059914-d966fc80-5fa1-11ea-98f9-a7869ec2d5b4.png)

**Comment by sancau** [comment]
Cell-based tags added in 0.1.7.
